### ISSUE TITLE
Auto-sync

### ISSUE THREAD

**Issue by DOKL57** [kevinmkchin/Obsidian-GitHub-Sync#1]
Hello, Kevin! Thanks for this useful plugin. Do you plan to add the ability to regularly auto-sync at a configured time?

**Comment by kevinmkchin** [comment]
Sure I can add it if I have some time this weekend.

**Comment by kevinmkchin** [comment]
I just pushed the auto sync feature in [the latest release](https://github.com/kevinmkchin/Obsidian-GitHub-Sync/releases/tag/1.0.2). It might take some time before the update shows up in Obsidian. You can configure how long you want your sync interval to be in the settings.

**Comment by kevinmkchin** [comment]
@DOKL57 I forgot to bump the package version. It's done now. Update should be available in Obsidian.
