### ISSUE TITLE
run first time with obsidian open

### ISSUE THREAD

**Issue by huahua-er** [kevinmkchin/Obsidian-GitHub-Sync#11]
Can the function of run once during the first obsidian start be added?

**Comment by Leka1B** [comment]
It was the developer's choice not to (or maybe that created some issues). Instead, the plugin checks if your repo has any changes and reminds you to sync them (in case you don't want to, i guess. That's a weird thing to do with notes but his choice)

**Comment by Leka1B** [comment]
It was the developer's choice not to (or maybe that created some issues). Instead, the plugin checks if your repo has any changes and reminds you to sync them.
I'll publish a fork with an option to do it in the settings

**Comment by kevinmkchin** [comment]
Released new version with @Leka1B's changes https://github.com/kevinmkchin/Obsidian-GitHub-Sync/releases/tag/1.0.5
