### ISSUE TITLE
Vault is not a Github Repo or git binary cannot be found. Problem Error: Error: TypeError [ERR_INVALID_ARG_VALUE]: The argument 'file' cannot be empty. Received"

### ISSUE THREAD

**Issue by PolyTyme** [kevinmkchin/Obsidian-GitHub-Sync#4]
I have a repo that I cloned to my system. I change one thing in the file and then press the button, but it gives me the error message as shown in the title.

Repo made through generic CLI
OS is Windows 10 Home
Error caused when doing nothing but pressing the button with a single file changed.

Github Username: my Github name
Github Key: Full Access to Everything in Repo
Github Repo format: "https://github.com/GithubUse.rname/RepoName.git" (not including the quotes)
Git binary is empty; Git is in the default location at ...\ProgramFiles\Git
Auto-sync: 0
(Shows the same error when the fields are all empty)

**Comment by ethanknights** [comment]
Experienced this too (on macOS)

**Comment by kevinmkchin** [comment]
Hi, could you try with the GitHub Repo field as: `github.com/GitHubUsername/RepoName.git`? without the https://

The reason for this is I just concatenate your username, key, and repo fields into one string that is used as the git remote, and for this concatenation to make sense the https:// needs to be gone.

**Comment by PolyTyme** [comment]
Yes, I've also tried it without .git and with the quotes for each variation.

**Comment by APinchofDill** [comment]
@PolyTyme Do you have windows ransomware protection in Windows defender enabled? I found the fix for me was to allow git.exe in the allowed apps. So add `C:\Program Files\Git\cmd\git.exe`

**Comment by PolyTyme** [comment]
No, that doesn't work. I already have windows defender fully disabled. I did add the exclusion though, and it still produced the same effect.

**Comment by PolyTyme** [comment]
Okay, the progress I've made has nearly succeeded until getting an error for merging files. "Merge conflicts in " This was the entire error. It did have to set origin in git remote, though. It also did merge my Obsidian changes to my repo on the first button press.
![Latest Error](https://github.com/kevinmkchin/Obsidian-GitHub-Sync/assets/164027940/4d7e4d25-637c-4e54-9427-50033f954f62)

For the steps I took to get to this point.

1. Even though git is in the default directory and visible from Command Prompt, it succeeded when I entered the directory manually and ended up with this new error.
![FirstError](https://github.com/kevinmkchin/Obsidian-GitHub-Sync/assets/164027940/276ca80c-3e00-4a23-9dc2-114f996f3864)

2. I renamed "!-Misc Software" to "-Misc Software" because I thought that might be causing some complications. 
3. Added the safe Directory

4. That led to the next error asking for my user.name and user.email. Which I followed.
![SecondError](https://github.com/kevinmkchin/Obsidian-GitHub-Sync/assets/164027940/15a4d110-2c61-4079-b933-1ced5da5de5a)

5. After that, I pressed the sync button and it went through, I missed a lot of the new errors that popped up, but afterwards I checked my repo and it had added the changes I made to the file I had opened on Obsidian, it didn't pull any other files' changes to Obsidian or push and of my other files that aren't in the repo.

6. I pressed the sync button again then it went through a longer process with different errors, one of the only ones not in this photo that I remember is it saying that there is no origin found in remote.
![Latest Error](https://github.com/kevinmkchin/Obsidian-GitHub-Sync/assets/164027940/4735ba37-1378-4065-ae9d-d236d7a1a800)

This is where I am at the moment. I'll reply with whatever significant progress.

**Comment by PolyTyme** [comment]
Note:
Pressing the button twice doesn't change anything.

**Comment by PolyTyme** [comment]
I moved my obsidian vault folder into a temp location in the same drive as Windows and Git.
I pressed the button, but it gave me the same error it's been showing. I used git status in the Obsidian vault directory, and Command Prompt gave me this error.
 "On branch master
nothing to commit, working tree clean".

This is the point at which I'm stumped and don't have a clear idea on how to solve.

**Comment by APinchofDill** [comment]
@PolyTyme Another thing was initialize the github directory. Do the initial push through git / or a tool like github desktop. Make sure it successfully pushes to github for the first time. For whatever reason the plugin was not finding git in the PATH system var. So I set the "optional" field to `C:\Program Files\Git\cmd\git.exe` in the settings. Also the repo has .git on the end of the URL without the https. Try that.

**Comment by PolyTyme** [comment]
Yep, I already did all that. I probably didn't make it clear in the comments.

**Comment by PolyTyme** [comment]
Alright, I made a brand new repo through CLI again, this time it is working perfectly, except it only pulls changes from the repo and not push any changes from Obsidian.

**Comment by PolyTyme** [comment]
It seems that it won't push because it claims that the password or username is invalid. (I used "Sign in With A Code" for signing in the first push)

In a new repo, It worked fine pushing and committing in CLI before assigning any variables with Github Sync.
This is still "progress" in the sense that I have an idea on why something is doing something.

**Comment by APinchofDill** [comment]
@PolyTyme In the plugin settings for Sync, did you generate the GitHub token? When committing through the plugin it requires an authentication token for access to GitHub api.

**Comment by PolyTyme** [comment]
# **SOLVED**

It turns out that the solution was simply the fact that I didn't have a .gitignore file to ignore the github-sync plugin and workspace.json in the obsidian files. The solution to the original question is that you have to manually put in the git location even if it's in the default location and is accessible from a terminal (C:/Program Files/Git/cmd/git.exe)

## _These are the full instructions for installing everything to work_

### 1.
Create a brand new repository from the GitHub browser. Make sure to include a .gitignore file (doesn't matter what kind, you'll be overwriting it in a moment) and a README file.
[This will be the repository that you'll be storing stuff, so make sure to name it what you want it to actually be]

### 2.
From the GitHub Browser, find the .gitignore file in the source code and edit it to have just this text in it 
`.obsidian/plugins
.obsidian/workspace.json
.obsidian/workspaces.json`
This will prevent git from getting stuck on trying to add your Personal Access Token due to security restrictions.
(You could also add the secret as an allowed secret instead, but that's not a good idea)

### 3.
Open Windows Command Prompt or Powershell.
Navigate to the location you want the Obsidian Notes to be in your computer using `cd C:\FirstFolder\SecondFolder\FinalFolder`.
Type `git clone https://github.com/Username/RepoName.git` This will put your repository onto your computer.
Navigate into that directory in your opened terminal.

### 4.
Open the vault from Obsidian. Make a single change to the README.md file's text.
Type `git --add .` in your terminal.
Type `git commit -m "Initial Obsidian Commit from CLI"`.
Type `git push -u origin main`. (main should be the name of your repo's branch)

### 5.
Install and Enable GitHub Sync plugin.
Insert values. (For the key, I used the Beta Fine Grained Token with full access to everything. I haven't tested with classic tokens)
--**DO NOTE PRESS SYNC YET**--
Do the same steps in step 4 starting at "git --add".

### 6.
You should then be able to press the sync button in Obsidian and have it working correctly.

## There are a few other errors that happen in the middle of these steps in the terminal. But they guide you through it themselves. 
Some of this might be superfluous, but I've had trouble when not doing these steps.

**Comment by sefatanam** [comment]
# For macOS (solution)

You just have to put the git binary location although it optional,
by running `which git` it will give you the git location. In my case git location is `/opt/homebrew/bin/git`
<img width="789" alt="Screenshot 2024-06-14 at 10 29 21 PM" src="https://github.com/kevinmkchin/Obsidian-GitHub-Sync/assets/37630292/72866026-02ca-44cd-a91d-0756206ac687">

After that it will works fine. But some common thing need to check before sync,
Assume that you already created git repo in github then don't forget to add these lines into `.gitignore` because it contain your github's personal access token which refuse by Github from exposing publicly.

```
.obsidian/plugins/github-sync/data.json // this is enough but you can also add the bellow or use pattern
.obsidian/plugins/github-sync/main.js
.obsidian/plugins/github-sync/manifest.json
.obsidian/plugins/github-sync/styles.css

```
basically that's it.
