### ISSUE TITLE
sync gitLocation between differ setup - broke sync. 

### ISSUE THREAD

**Issue by azhestov** [kevinmkchin/Obsidian-GitHub-Sync#8]
When you have for example Linux and Windows setup, any time when you sync - git path in settings changes and all stop work. So "gitLocation" in data.json must be possible to exclude from sync process or turn to host depend variable.

**Comment by azhestov** [comment]
possible temporary solution - make environment variable called for example GIT with full git path and write "GIT" in git path settings.

**Comment by kevinmkchin** [comment]
you can exclude data.json from syncing by adding it to a `.gitignore`:
``` .gitignore
.obsidian/plugins/github-sync/data.json
```
