### ISSUE TITLE
Merge conflicts

### ISSUE THREAD

**Issue by DrP1ng** [kevinmkchin/Obsidian-GitHub-Sync#9]
I'm having a problem when I run "Sync with Remote". I get a message saying "Merge conflicts in: Resolve them or click sync button again push with unresolved conflicts." but whenever I click "Sync with Remote" again the same message is repeated. I also check the GitHub directory and it is empty (just a README.md file that I created).

![2024-08-08_22-02](https://github.com/user-attachments/assets/d8e85d46-5484-49ba-bf12-0e64403efb67)
![2024-08-09_09-18](https://github.com/user-attachments/assets/8ace3373-d002-45b4-befb-bb366f6fee71)

Any ideas?

**Comment by jisotalo** [comment]
Same thing here. Testing this for the first time. 

I also manually pushed everything to the remote using git (so branch is up-to-date), but still the same error when pressing sync. There are no conflicts.

**Comment by kevinmkchin** [comment]
> Same thing here. Testing this for the first time. 
> 
> 
> 
> I also manually pushed everything to the remote using git (so branch is up-to-date), but still the same error when pressing sync. There are no conflicts.

IVE BEEN NEGLECTING THIS PLUGIN FOR LIKE MONTHS I WILL TAKE A LOOK AT YALLS ISSUES SOON

**Comment by kevinmkchin** [comment]
Ok so these actually aren't merge conflicts it's just bad error messages. Something else went wrong during `git pull` potentially due to the remote URL being invalid.

I've updated the package to be way simpler to set up. Feel free to try again.
